<Project Sdk="Microsoft.NET.Sdk">


  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\Byteqon.Application\Byteqon.Application.csproj" />
    <ProjectReference Include="..\Byteqon.Domain\Byteqon.Domain.csproj" />
  </ItemGroup>

</Project>
